@baseUrl = http://localhost:3000/api

### STAT ADMINS ###
GET {{baseUrl}}/admin/stat?useView=true
################################################################

### ROUTES OWORLD ###
### Data world ###
GET {{baseUrl}}/oworld?useView=false

### List country ###
GET {{baseUrl}}/oworld?useView=true

### List flags ###
GET {{baseUrl}}/oworld/flags

### One country ###
GET {{baseUrl}}/oworld/FRA

### Categories by country ###
GET {{baseUrl}}/oworld/FRA/category

### ROUTES USERS ###
### Add User ###
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "&Test1234",
  "country_origin": 1,
  "birth_date": "1938-06-16"
}

### Profile ###
GET {{baseUrl}}/user/601
### Add Favorite ###
POST {{baseUrl}}/user/1/FRA
### Delete Favorite ###
DELETE {{baseUrl}}/user/1/FRA
### Update User ###
PUT {{baseUrl}}/user/1
Content-Type: application/json

{
  "username": "Bob",
  "email": "test@test1.com",
  "password": "&Test1234"
}
### Delete User ###
DELETE {{baseUrl}}/user/1

### ROUTES LOGIN/OUT ###
### Login to user ###
POST {{baseUrl}}/log/in
Content-Type: application/json

{
  "email": "test@test1.com",
  "password": "&Test1234"
}
### Logout ###
GET {{baseUrl}}/log/out
