@baseUrl = http://localhost:3000/api
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

# @name login
POST {{baseUrl}}/log/in
content-type: application/x-www-form-urlencoded

username=Loic&password=%26Tets1234

### Marche pas
GET {{baseUrl}}/user/601

### Marche
GET {{baseUrl}}/user/601/
Authorization: Bearer {{accessToken}}
### Add Favorite ###
POST {{baseUrl}}/user/601/FRA
Authorization: Bearer {{accessToken}}
### Delete Favorite ###
DELETE {{baseUrl}}/user/601/FRA
Authorization: Bearer {{accessToken}}

### STAT ADMINS ###
GET {{baseUrl}}/admin/601/stat?useView=true
Authorization: Bearer {{accessToken}}
################################################################

###
POST {{baseUrl}}/log/refresh-token
Authorization: Bearer {{accessToken}}
content-type: application/x-www-form-urlencoded

refreshToken={{refreshToken}}

###
POST {{baseUrl}}/log/reset-password
content-type: application/json

{
  "email":"test@test.com"
}
