@baseUrl = http://localhost:3000/api

### STAT ADMINS ###
GET {{baseUrl}}/admin/601/stat?useView=true
################################################################

### ROUTES OWORLD ###
### Data world ###
GET {{baseUrl}}/oworld?useView=false

### List country ###
GET {{baseUrl}}/oworld/list?useView=true

### List flags ###
GET {{baseUrl}}/oworld/flags

### One country ###
GET {{baseUrl}}/oworld/ABC

### Categories by country ###
GET {{baseUrl}}/oworld/LUX/category

### WTF by country ###
GET {{baseUrl}}/oworld/CHN/wtf

### ROUTES USERS ###
### Add User ###
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "Loic",
  "email": "test@test.com",
  "password": "&Tets1234",
  "country_origin": 1,
  "birth_date": "1938-06-16"
}

### Profile ###
GET {{baseUrl}}/user/601
### Add Favorite ###
POST {{baseUrl}}/user/601/BEL
### Delete Favorite ###
DELETE {{baseUrl}}/user/601/FRA
### Update User ###
PUT {{baseUrl}}/user/601
Content-Type: application/json

{
  "username": "Loic",
  "email": "test@test.com",
  "password": "Test&1234"
}
### Delete User ###
DELETE {{baseUrl}}/user/601

### ROUTES LOGIN/OUT ###
### Login to user ###
POST {{baseUrl}}/log/in
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test&1234"
}

### Logout ###
GET {{baseUrl}}/log/out


### TESTS JWT
### Login to user ###
POST {{baseUrl}}/log/in
content-type: application/x-www-form-urlencoded

username=Loic&password=Test%261234

### Check authorization ###
GET {{baseUrl}}/user/601
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsInVzZXJuYW1lIjoiTG9pYyIsInJvbGVzIjpbIlVzZXIiXSwicGVybWlzc2lvbnMiOlsiRGVsZXRlIiwiUmVhZCIsIlVwZGF0ZSJdfSwiaWF0IjoxNjg2ODM2MjY5LCJleHAiOjE2ODY4MzcxNjl9.1GT2j58AYAfsE3xUhrD9sa0NbM7ho9wUoMkLmbbrFFk

### Get Token refresh ###
POST {{baseUrl}}/log/in
content-type: application/x-www-form-urlencoded

username=Loic&password=Test%261234