@baseUrl = https://restcountries.com/v3.1/
@ISO = FRA
@language = spanish
@region = europe
@subregion = Northern Europe

@param = alpha

@fields = name,capital,region,languages

### Tous les pays 
GET {{baseUrl}}/all

### Un pays
GET {{baseUrl}}/alpha/{{ISO}}

### Par langue
GET {{baseUrl}}/lang/{{language}}

### Par région
GET {{baseUrl}}/region/{{region}}

### Par sous-région
GET {{baseUrl}}/subregion/{{subregion}}

### Avec filtre
{{baseUrl}}//{{param}}/{{ISO}}?fields=languages,population,flags,coatOfArms

### Avec filtre et paramètre
{{baseUrl}}/{{param}}/{{ISO}}?fields={{fields}}


###
GET {{baseUrl}}/all?fields=languages
###
GET {{baseUrl}}/all?fields=region

### Par sous-région
GET {{baseUrl}}/region/{{region}}?fields=subregion